docker-compose.yml
version: "3.3"

services:
  database:
    container_name: tst_django1_databse
    image: postgres
    restart: always
    volumes:
      - ./.pagdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=pythonpro
      - POSTGRES_USER=pythonpro
    ports:
      - 5434:5432
